// File is included in mission framework
private _isOfficer = _type == "Officer";
private _isSquadLeader = _type == "Squad Leader";
private _isTeamLeader = _type == "Team Leader";
private _isRifleman = _type == "Rifleman";
private _isRiflemanAT = _type == "Rifleman (AT)";
private _isMarksman = _type == "Marksman" || _type == "Sharpshooter";
private _isAutorifleman = _type == "Autorifleman";
private _isAutoriflemanAsst = _type == "Asst. Autorifleman";
private _isLifeSaver = _type == "Combat Life Saver";
private _isGrenadier = _type == "Grenadier";
private _isHelicopterPilot = _type == "Helicopter Pilot";
private _isHelicopterCrew = _type == "Helicopter Crew";
private _isEngineer = _type == "Engineer" || _type == "Repair Specialist";
private _isCrewman = _type == "Crewman";
private _isPilot = _type == "Pilot";
private _isRTO = _type == "JTAC" || _type == "Recon JTAC";
private _isReconLeader = _type == "Recon Team Leader";
private _isRecon = _type == "Recon Scout";
private _isReconDemo = _type == "Recon Demo Specialist";
private _isReconMedic = _type == "Recon Paramedic";
private _isReconAT = _type == "Recon Scout (AT)";
private _isReconMarksman = _type == "Recon Marksman";
private _isDemo = _type == "Explosive Specialist";
private _isHMG = _type == "Gunner (HMG)";
private _isStaticAT = _type == "Gunner (AT)";
private _isUAVOperator = _type == "UAV Operator";
private _isHMGTripod = _type == "Asst. Gunner (HMG/GMG)";
private _isATTripod = _type == "Asst. Gunner (AT)";
private _isMortar = _type == "Gunner (Mk6)";
private _isMortarAssistant = _type == "Asst. Gunner (Mk6)";
private _isWeaponsAT = _type == "Missile Specialist (AT)";
private _isWeaponsATAssistant = _type == "Asst. Missile Specialist (AT)";
private _isWeaponsAA = _type == "Missile Specialist (AA)";
private _isWeaponsAAAssistant = _type == "Asst. Missile Specialist (AA)";
private _isSniper = _type == "Sniper";
private _isSpotter = _type == "Spotter";
private _isMMG = _type == "Heavy Gunner";
private _isMMGAsst = _type == "Ammo Bearer";
