
_isOfficer = (_type == "CO")||(_type == "Officer");
_isSquadLeader = (_type == "SL")||(_type == "Squad Leader");
_isTeamLeader = (_type == "FTL")||(_type == "Team Leader");
_isRifleman = (_type == "rifleman")||(_type == "Rifleman");
_isRiflemanAT = (_type == "at")||(_type == "Rifleman (AT)");
_isMarksman = (_type == "marksman")||(_type == "Marksman")||(_type == "Sharpshooter");
_isAutorifleman = (_type == "mg")||(_type == "Autorifleman");
_isAutoriflemanAsst = (_type == "Asst. Autorifleman");
_isLifeSaver = (_type == "medic")||(_type == "Combat Life Saver");
_isGrenadier = (_type == "grenadier")||(_type == "Grenadier");
_isHelicopterPilot = (_type == "helipilot")||(_type == "Helicopter Pilot");
_isHelicopterCrew = (_type == "helicrew")||(_type == "Helicopter Crew");
_isEngineer = (_type == "engineer")||(_type == "Engineer")||(_type == "Repair Specialist");
_isCrewman = (_type == "crew")||(_type == "driver")||(_type == "gunner")||(_type == "commander")||(_type == "loader")||(_type == "Crewman");
_isPilot = (_type == "pilot")||(_type == "Pilot");
_isRTO = (_type == "RTO")||(_type == "JTAC")||(_type == "Recon JTAC");
_isReconLeader = (_type == "reconleader")||(_type == "Recon Team Leader");
_isRecon = (_type == "recon")||(_type == "Recon Scout");
_isReconDemo = (_type == "recondemo")||(_type == "Recon Demo Specialist");
_isReconMedic = (_type == "reconmedic")||(_type == "Recon Paramedic");
_isDemo = (_type == "demo")||(_type == "Explosive Specialist");
_isHMG = (_type == "hmg")||(_type == "Gunner (HMG)");
_isStaticAT = (_type == "staticAT");
_isUAVOperator = (_type == "uav")||(_type == "UAV Operator");
_isHMGTripod = (_type == "hmgtripod")||(_type == "Asst. Gunner (HMG/GMG)");
_isATTripod = (_type == "attripod")||(_type == "Asst. Missile Specialist (AT)");
_isMortar = (_type == "mortar") || (_type == "Gunner (Mk6)");
_isMortarAssistant = (_type == "mortarasst") || (_type == "Asst. Gunner (Mk6)");
_isHeavyAT = (_type == "hat")||(_type == "Missile Specialist (AT)");
_isATAssistant = (_type == "hatast")||(_type == "Ammo Bearer (AT)");
_isSniper = (_type == "sniper")||(_type == "Sniper");
_isSpotter = (_type == "spotter")||(_type == "Spotter");
_isMMG = (_type == "mmg")||(_type == "Heavy Gunner");
_isMMGAsst = (_type == "mmgasst")||(_type == "Ammo Bearer");
