
#define FACTION_INFO 0

#define FACTION_SIDE 0
#define FACTION_COLOR 1
#define FACTION_NAME 2
#define FACTION_CALLSIGNS 3

#define FACTION_VEHICLES 4
#define FACTION_OBJECTS 5
#define FACTION_SKILL 6

#define FACTION_OBJECTS_FLAG 0
#define FACTION_OBJECTS_CRATES 1
#define FACTION_OBJECTS_WALLS 2
#define FACTION_OBJECTS_STRUCTURES 3

#define FACTION_OBJECTS_CAMPS_BASIC 4
#define FACTION_OBJECTS_CAMPS_OBJECTS 5
#define FACTION_OBJECTS_CAMPS_WALLS 6
#define FACTION_OBJECTS_CAMPS_AMMO 7

#define CAMP_BASIC 0
#define CAMP_OBJECTS 1
#define CAMP_WALLS 2
#define CAMP_AMMO 3

#define CAMP_RET_BASIC 0
#define CAMP_RET_OBJECTS 1
#define CAMP_RET_STATIC 2
#define CAMP_RET_GUARDS 3
#define CAMP_RET_WALLS 4
#define CAMP_RET_AMMO 5