// File is included in mission framework
#define FACTION_OBJECTS_FLAG 0
#define FACTION_OBJECTS_CRATES 1
#define FACTION_OBJECTS_WALLS 2
#define FACTION_OBJECTS_STRUCTURES 3

#define FACTION_OBJECTS_CAMPS_BASIC 4
#define FACTION_OBJECTS_CAMPS_OBJECTS 5
#define FACTION_OBJECTS_CAMPS_WALLS 6
#define FACTION_OBJECTS_CAMPS_AMMO 7

#define CAMP_BASIC 0
#define CAMP_OBJECTS 1
#define CAMP_WALLS 2
#define CAMP_AMMO 3
#define CAMP_STATICS 4

#define CAMP_RET_BASIC 0
#define CAMP_RET_OBJECTS 1
#define CAMP_RET_STATIC 2
#define CAMP_RET_GUARDS 3
#define CAMP_RET_WALLS 4
#define CAMP_RET_AMMO 5
