
#define AA_VEHICLES 0
#define ATTACK_HELOS 1
#define ATTACK_PLANES 2
#define HEAVY_VEHICLES 3
#define LIGHT_VEHICLES 4
#define MEDIUM_VEHICLES 5
#define MOBILE_ARTILLERY 6
#define TRANSPORT_HELOS 7
#define TRANSPORT_PLANES 8
#define TRANSPORT_TRUCKS 9
#define STATIC_DEFENSE 10
#define BOATS 11
#define UAV 12
#define UGV 13
#define SUPPORT 14
#define SUBMARINES 15
#define MRAP_VEHICLES 16