#include "defines.hpp"
#include "dialogs\defines.hpp"

#include "dialogs\login.hpp"
#include "dialogs\main.hpp"
#include "dialogs\conditions.hpp"
#include "dialogs\input.hpp"
#include "dialogs\playerMenu.hpp"
#include "dialogs\taskMenu.hpp"
#include "dialogs\debug.hpp"
